<a href="https://colab.research.google.com/github/Riddhi180605/Internship_Work/blob/main/1_multi_array.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
x = np.random.randint(1,20,(3,3,3))
x

array([[[10,  4,  8],
        [16,  5,  2],
        [15,  8, 17]],

       [[16,  9, 10],
        [17,  8,  6],
        [ 4, 11,  6]],

       [[ 9,  8,  8],
        [ 3,  8,  6],
        [ 2, 15,  8]]])

In [ ]:
print(np.min(x))
print(np.min(x,axis = 1))
print(np.min(x,axis = 0))

2
[[10  4  2]
 [ 4  8  6]
 [ 2  8  6]]
[[9 4 8]
 [3 5 2]
 [2 8 6]]


In [ ]:
print(np.max(x))
print(np.max(x,axis = 1))
print(np.max(x,axis = 0))

17
[[16  8 17]
 [17 11 10]
 [ 9 15  8]]
[[16  9 10]
 [17  8  6]
 [15 15 17]]


In [ ]:
print(np.mean(x))
print(np.mean(x,axis = 1))
print(np.mean(x,axis = 0))

8.851851851851851
[[13.66666667  5.66666667  9.        ]
 [12.33333333  9.33333333  7.33333333]
 [ 4.66666667 10.33333333  7.33333333]]
[[11.66666667  7.          8.66666667]
 [12.          7.          4.66666667]
 [ 7.         11.33333333 10.33333333]]


In [ ]:

ans = np.sum(x)
print(ans)
ans = np.sum(x,axis=0)
print(ans) # col vise
ans = np.sum(x,axis=1)
print(ans) # row vise

239
[[35 21 26]
 [36 21 14]
 [21 34 31]]
[[41 17 27]
 [37 28 22]
 [14 31 22]]


In [ ]:
print(x.shape)
print(x.ndim)
print(x.size)
print(x.dtype)

(3, 3, 3)
3
27
int64


In [ ]:
x = np.zeros((5,2,3))
print(x)

[[[0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]]]


In [ ]:
x = np.ones((2,3,2))
print(x)

[[[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]]


In [ ]:
x = np.full((2,2,3),fill_value= 11)
print(x)

[[[11 11 11]
  [11 11 11]]

 [[11 11 11]
  [11 11 11]]]


In [ ]:
x = np.empty(shape = (2,3,2))
print(x)

[[[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]]
