<a href="https://colab.research.google.com/github/Riddhi180605/Internship_Work/blob/main/flatten.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np


In [ ]:

a = np.arange(12).reshape(3,4)
print(a)
print(a.shape)

a1 = a.flatten()
print(a1)
print(a1.shape)



[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
(3, 4)
[ 0  1  2  3  4  5  6  7  8  9 10 11]
(12,)


In [ ]:
x1 = np.arange(24).reshape(4,3,2)
print(x1)
print(x1.shape)

b2 = x1.flatten()
print(b2)
print(b2.shape)




[[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]

 [[12 13]
  [14 15]
  [16 17]]

 [[18 19]
  [20 21]
  [22 23]]]
(4, 3, 2)
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
(24,)


In [ ]:
x3 = np.arange(12).reshape(4,3)
print(x3)

# column

b3 =  x3.flatten(order="F")
print(b3)
print(b3.shape)


# row
b4 = x3.flatten(order="C")
print(b4)
print(b4.shape)

# memory order
b4 = x3.flatten(order="K")
print(b4)
print(b4.shape)



[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[ 0  3  6  9  1  4  7 10  2  5  8 11]
(12,)
[ 0  1  2  3  4  5  6  7  8  9 10 11]
(12,)
[ 0  1  2  3  4  5  6  7  8  9 10 11]
(12,)
