<a href="https://colab.research.google.com/github/Riddhi180605/Internship_Work/blob/main/slicing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
arr = np.array([1,2,3,4,5,6,7,8,9,10])
#1  2  3  4  5  --> values
#0  1  2  3  4 --> index
#-5 -4 -3 -2 -1 --> reverse index
print(arr)

[ 1  2  3  4  5  6  7  8  9 10]


In [ ]:
print(arr[1])

2


In [ ]:
print(arr[-1])

10


In [ ]:
print(arr[1:])

[ 2  3  4  5  6  7  8  9 10]


In [ ]:
print(arr[:3])

[1 2 3]


In [ ]:
print(arr[:-1])

[1 2 3 4 5 6 7 8 9]


In [ ]:
print(arr[0:10:2])

[1 3 5 7 9]


In [ ]:
print(arr[::2])

[1 3 5 7 9]


In [ ]:
print(arr[:-1])

[1 2 3 4 5 6 7 8 9]


In [ ]:
print(arr[1:10])

[ 2  3  4  5  6  7  8  9 10]


In [ ]:
print(arr[:10000])

[ 1  2  3  4  5  6  7  8  9 10]
