<a href="https://colab.research.google.com/github/Riddhi180605/Internship_Work/blob/main/task1Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

**1. Array Creation :**

Create a NumPy array of numbers from 1 to 20. Then print its size.

In [ ]:
arr = np.arange(21)
print(arr)
print("Size : " ,arr.size)



[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
Size :  21


**2. Zeros & Ones**

Create :

a 3×4 array filled with zeros

a 2×5 array filled with ones


In [ ]:
arr = np.zeros((3,4))
print("Zeros array is : \n" ,arr)
print("\n")
arr1 = np.ones((2,5))
print("Ones array is : \n" ,arr1)

Zeros array is : 
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


Ones array is : 
 [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


**3. Full Function**

Create a 4×4 array where every value is 7 using NumPy.

In [ ]:
arr = np.full((4,4),7)
print(arr)

[[7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]]


**4. Reshape**

Create an array from 1 to 12 and reshape it into:

3×4

2×6

In [ ]:
arr = np.arange(1,13).reshape(3,4)
print(arr)
print("\n")
arr = np.arange(1,13).reshape(2,6)
print(arr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]



**5. Flatten**

Take a 3×3 matrix and convert it into a 1D array using flatten.

In [ ]:
arr = np.arange(1,10).reshape(3,3)
print(arr)
arr1 = arr.flatten()
print(arr1)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[1 2 3 4 5 6 7 8 9]


**6. Arrange (arange)**

Create an array starting from 10 to 50 with a step of 5.

In [ ]:
arr = np.arange(10,51,5)
print(arr)

[10 15 20 25 30 35 40 45 50]



**7. Sum of Elements**

Given array:

[10, 20, 30, 40, 50]

Find:

total sum

sum of first 3 elements only

In [ ]:
arr = np.array([10, 20, 30, 40, 50])
print("Total Sum : ", np.sum(arr))
print("\n")
print("First 3 ele sum is : " ,np.sum(arr[:3]))

Total Sum :  150


First 3 ele sum is :  60


**8. Matrix Addition**

Add the following two arrays:

A = [[1,2,3],
     [4,5,6]]


B = [[6,5,4],
     [3,2,1]]

In [ ]:
A = np.arange(1,7).reshape(2,3)
B = np.arange(6,0,-1).reshape(2,3)
print(A+B)

[[7 7 7]
 [7 7 7]]


**9. Matrix Subtraction**

Subtract array B from array A (from Q8).

In [ ]:
print(A-B)

[[-5 -3 -1]
 [ 1  3  5]]


**10. Element-wise Multiplication**

Multiply arrays A and B element by element.

In [ ]:
print(A*B)

[[ 6 10 12]
 [12 10  6]]


**11. Mean**

Find the mean of:

[12, 15, 20, 25, 30]

In [ ]:
arr = np.array([12, 15, 20, 25, 30])
print(np.mean(arr))

20.4




**12. Median**

Find the median of:

[5, 2, 9, 1, 7, 6]


In [ ]:
arr = np.array([5, 2, 9, 1, 7, 6])
print(np.median(arr))

5.5



**13. Standard Deviation**

Find the standard deviation of:

[4, 8, 6, 5, 3, 7]



In [ ]:
arr = np.array([4, 8, 6, 5, 3, 7])
print(np.std(arr))

1.707825127659933


**14. Row-wise Sum**

Given matrix:

[[1,2,3],
 [4,5,6],
 [7,8,9]]

Find sum of each row separately.






In [ ]:
arr = np.arange(1,10).reshape(3,3)
print(arr)
print("\n")
print(np.sum(arr,axis=1))

[[1 2 3]
 [4 5 6]
 [7 8 9]]


[ 6 15 24]


**15. Column-wise Sum**

Using the same matrix from Q14, find sum of each column.

In [ ]:
print(np.sum(arr,axis=0))

[12 15 18]


**16. Reshape + Mean**

Create numbers from 1 to 16, reshape into 4×4, then find the mean of each row.



In [ ]:
arr = np.arange(1,17).reshape(4,4)
print(arr)
print("\n")
print(np.mean(arr,axis=1))

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


[ 2.5  6.5 10.5 14.5]


**17. Flatten + Size**

Create a 5×5 ones matrix. Flatten it and find its size.


In [ ]:
arr = np.ones((5,5))
arr1 = arr.flatten()
print(arr1.size)

25



**18. Arithmetic Combination**

Given:

A = [1,2,3,4]

B = [5,6,7,8]

Compute:

(A + B) * 2



In [ ]:
A = np.array([1,2,3,4])
B = np.array([5,6,7,8])
print((A+B)*2)

[12 16 20 24]


**19. Mixed Operations**

Create array from 1–9, reshape to 3×3. Multiply entire matrix by 5 and then find total sum.



In [ ]:
arr = np.arange(1,10).reshape(3,3)
arr1 = arr*5
print("\n")
print(np.sum(arr1))



225


**20. Statistics Combo**

Given:

[15, 18, 21, 24, 27, 30]

Find:

mean

median

standard deviation

In [ ]:
arr = np.arange(15,31,3)
print("Mean : " , np.mean(arr))
print("Median : " , np.median(arr))
print("Standard Deviation  : " , np.std(arr))

Mean :  22.5
Median :  22.5
Standard Deviation  :  5.123475382979799


**1. Advanced Reshape + Sum**

Create an array from 1 to 48.

Reshape it into 4 × 4 × 3.

Find:

sum along axis 0

sum along axis 1

sum along axis 2



In [ ]:
arr = np.arange(1,49).reshape(4,4,3)
print("Array is : \n",arr)
print("\n")
print("Sum according to axis 0 : \n",np.sum(arr,axis = 0))
print("\n")
print("Sum according to axis 1 : \n",np.sum(arr,axis = 1))
print("\n")
print("Sum according to axis 2 : \n",np.sum(arr,axis = 2))

Array is : 
 [[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]
  [10 11 12]]

 [[13 14 15]
  [16 17 18]
  [19 20 21]
  [22 23 24]]

 [[25 26 27]
  [28 29 30]
  [31 32 33]
  [34 35 36]]

 [[37 38 39]
  [40 41 42]
  [43 44 45]
  [46 47 48]]]


Sum according to axis 0 : 
 [[ 76  80  84]
 [ 88  92  96]
 [100 104 108]
 [112 116 120]]


Sum according to axis 1 : 
 [[ 22  26  30]
 [ 70  74  78]
 [118 122 126]
 [166 170 174]]


Sum according to axis 2 : 
 [[  6  15  24  33]
 [ 42  51  60  69]
 [ 78  87  96 105]
 [114 123 132 141]]


**2. Conditional Replacement**

Create array from 1 to 20.

Replace all numbers:

divisible by 3 → -1

divisible by 5 → 100

(Do it using NumPy, not loops.)


In [ ]:
arr = np.arange(1,21)
# method 1 :
# arr[arr%3==0] = -1
# arr[arr%5==0] = 100
# print(arr)

# method 2 :
arr = np.where(arr%3==0,-1,arr)
arr = np.where(arr%5==0,100,arr)
print(arr)

[  1   2  -1   4 100  -1   7   8  -1 100  11  -1  13  14  -1  16  17  -1
  19 100]


**3. Broadcasting Math**

Given:

A = np.array([[1,2,3],[4,5,6],[7,8,9]])


B = np.array([10,20,30])

Add B to every row of A using broadcasting.




In [ ]:
A = np.arange(1,10).reshape(3,3)
B = np.arange(10,40,10)
print(A+B)

[[11 22 33]
 [14 25 36]
 [17 28 39]]


**4. Flatten vs Ravel Logic**

Create a 3×3 matrix.

Use ravel() to flatten and modify the first element.

Then check whether original array changes.

Explain why.

In [ ]:
arr = np.arange(1,10).reshape(3,3)
arr1 = arr.ravel()
arr1[0] = 100
print("Ravel : \n " ,arr)
arr1 = arr.flatten()
arr1[1] = 100
print("Flatten : \n " ,arr)

# ravel() returns a view of the original array, so modifying it affects the original array, whereas flatten() returns a copy.

Ravel : 
  [[100   2   3]
 [  4   5   6]
 [  7   8   9]]
Flatten : 
  [[100   2   3]
 [  4   5   6]
 [  7   8   9]]


**5. Indexing Challenge**

Create array 1–25 and reshape to 5×5.

Extract:

middle row

last column

corner elements only


In [ ]:
arr = np.arange(1,26).reshape(5,5)
print(arr)
print("\n")
print(arr[2])
print("\n")
print(arr[:,-1])
print("\n")
# print(arr[[0,0,-1,-1],[0,-1,0,-1]])  # m -1
print(arr[::4,::4].flatten()) # m-2

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


[11 12 13 14 15]


[ 5 10 15 20 25]


[ 1  5 21 25]


**6. Statistical Axis Problem**

Given:

arr = np.array([[10,20,30],
                [40,50,60],
                [70,80,90]])

Find:

mean of each column

standard deviation of each row


In [ ]:
arr = np.arange(10,100,10).reshape(3,3)
print("Mean of each col is : ",np.mean(arr,axis = 0))
print("Standard Deviation of each row is : ",np.std(arr,axis = 1))

Mean of each col is :  [40. 50. 60.]
Standard Deviation of each row is :  [8.16496581 8.16496581 8.16496581]


**7. Matrix Arithmetic Combo**

Create two random 3×3 arrays.

Compute:

(A + B) * 2 - A





In [ ]:
A = np.random.rand(3,3)
B = np.random.rand(3,3)
print((A+B)*2-A)

[[1.35374171 1.74887502 1.91055285]
 [0.50848043 0.79122893 0.88265694]
 [0.65712706 1.28771419 0.73222085]]


**8. Pattern Matrix**

Create this matrix using NumPy only:

[[1,0,1,0],
 [0,1,0,1],
 [1,0,1,0],
 [0,1,0,1]]

(No manual typing.)

In [ ]:
arr = np.ones((4,4),dtype = 'int')
arr[::2,1::2] = 0
arr[1::2,::2] = 0
print(arr)

[[1 0 1 0]
 [0 1 0 1]
 [1 0 1 0]
 [0 1 0 1]]


**9. 3D Array Stats**

Create array from 1–27 and reshape to 3×3×3.

Find:

overall mean

mean along axis 0

median of entire array



In [ ]:
arr = np.arange(1,28).reshape(3,3,3)
print("Mean : ",np.mean(arr))
print("\n")
print("Mean along side axis 0 : \n",np.mean(arr,axis = 0))
print("\n")
print("Median : ",np.median(arr))

Mean :  14.0


Mean along side axis 0 : 
 [[10. 11. 12.]
 [13. 14. 15.]
 [16. 17. 18.]]


Median :  14.0


**10. Multi-step Transformation**

Create array from 1–16.

Steps:

Reshape to 4×4

Multiply each column by [1,2,3,4]

Flatten result

Find standard deviation

In [ ]:
arr = np.arange(1,17).reshape(4,4)
print("Array is : \n",arr)
print("\n")
arr1 = arr*np.arange(1,5)
print("Array after multiplication : \n",arr1)
print("\n")
arr2 = arr1.flatten()
print("Array after flattening : \n",arr2)
print("\n")
print("Standard Deviation : ",np.std(arr2))

Array is : 
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


Array after multiplication : 
 [[ 1  4  9 16]
 [ 5 12 21 32]
 [ 9 20 33 48]
 [13 28 45 64]]


Array after flattening : 
 [ 1  4  9 16  5 12 21 32  9 20 33 48 13 28 45 64]


Standard Deviation :  17.38533865071371


In [ ]:
arr = np.ones((5,5),dtype = 'int')
print("Array is : \n",arr)

arr[1:4,1:4] = 0
arr[2,2] = 9


print("\n")
print("New updated Array is : \n",arr)


# import numpy as np
# y = np.ones(16 , dtype=int).reshape(4,4)
# print(y)

# y[::2,::2] = 0
# y[1:4:2,1:4:2] = 0

# print("\n\n", y)


Array is : 
 [[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]


New updated Array is : 
 [[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 9 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]
