<a href="https://colab.research.google.com/github/Riddhi180605/Internship_Work/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
x = np.array([10,20,30,40,50])
print(x)


[10 20 30 40 50]


In [ ]:
x = np.zeros(5)
print(x)

[0. 0. 0. 0. 0.]


In [ ]:
x = np.zeros((2,3))
print(x)

[[0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
x = np.zeros(5,dtype=int)
print(x)

[0 0 0 0 0]


In [ ]:
x = np.ones(5,dtype=int)
print(x)

[1 1 1 1 1]


In [ ]:
x = np.full(5,fill_value= 11)
print(x)

[11 11 11 11 11]


In [ ]:
x = np.full(10,7)
print(x)

[7 7 7 7 7 7 7 7 7 7]


In [ ]:
x = np.empty(shape = (2,3))
print(x)

[[0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
x = np.array([[10,20,30],[40,50,60]])
#x = np.array([10,20,30,40,50,60,70,80,90,100])
print(x)
print(x.shape)
print(x.ndim)
print(x.size)
print(x.dtype)

[[10 20 30]
 [40 50 60]]
(2, 3)
2
6
int64


In [ ]:
x = np.array([1,2,3])
y = np.array([4,5,6])
print(x+y)

[5 7 9]


In [ ]:
x = np.array([[1,2,3],[4,5,6]])
y = np.array([[1,2,3],[4,5,6]])
print(x+y)

[[ 2  4  6]
 [ 8 10 12]]


In [ ]:
x = np.array([[1,2,3],[4,5,6]])
y = np.array([[1,2,3],[4,5,6]])

ans = np.sum(x)
print(ans)
ans = np.sum(x+y)
print(ans)



21
42


In [ ]:
x = np.array([[1,2,3],[4,5,6]])

ans = np.sum(x)
print(ans)
ans = np.sum(x,axis=0)
print(ans) # col vise
ans = np.sum(x,axis=1)
print(ans) # row vise


21
[5 7 9]
[ 6 15]


In [ ]:
x = np.array([[1,2,3],[4,5,6]])
y = np.array([[1,2,3],[4,5,6]])
ans = np.sum(x+y)
print(ans)
ans = np.sum((x+y),axis=0)
print(ans) # col vise
ans = np.sum((x+y),axis=1)
print(ans) # row vise

42
[10 14 18]
[12 30]


In [ ]:
x = np.array([1,2,3,4,5,6,7,8,8])
ans = np.mod(x,2)
print(ans)

[1 0 1 0 1 0 1 0 0]


In [ ]:
x = np.array([1,2,3,4,5,6,7,8,8])
ans = np.std(x)
print(ans)

2.4241582476968255


In [ ]:
x = np.array([1,2,3,4,5,6,7,8,8])
ans = np.min(x)
print(ans)
x = np.array([[1,2,3],[4,5,6],[7,8,9]])
ans1 = np.min(x,axis = 0)
print(ans1)
ans2 = np.min(x,axis = 1)
print(ans2)

1
[1 2 3]
[1 4 7]


In [ ]:
x = np.array([1,2,3,4,5,6,7,8,8])
ans = np.max(x)
print(ans)

8
